LICENSE.md

Addressing https://github.com/anriseth/LineSearches.jl/commit/582b61276bf0ed978809bba97a0d77e858fe5ed4#commitcomment-19450850
I have added the MINPACK license here @tkelman. I'm not so familiar with licensing issues, is this the correct way to do it?

Update LICENSE.md with MINPACK copyright

---

test/optim.jl
test/runtests.jl

Requires Optim master at the moment. Waiting to merge until the next version of Optim. Closes #15

Testing that uses Optim

---

NEWS.md
README.md
src/LineSearches.jl
src/basic.jl
test/alphacalc.jl
test/optim.jl
test/runtests.jl

Add basic linesearch

---

test/counter.jl
test/runtests.jl

Test that all the linesearches algorithms send back the correct fcounts to Optim result.

Add fcount, gcount tests

---

src/morethuente.jl

Returns step if we find `g(x+alpha*step) == 0` for morethuente. We should add the gtol from Optim in the future and check `|g(x+alpha*step)| < gtol` #35 
Fixes v0.6 errors.

morethuente return if g(x) == 0

---

test/alphacalc.jl
test/backtracking.jl
test/counter.jl
test/optim.jl
test/runtests.jl

~~Need to deal with all the new PRs first~
Should be fine actually

Use @testsets 

---

src/deprecate.jl
src/hagerzhang.jl

Fix bugs found in https://github.com/JuliaNLSolvers/Optim.jl/pull/407

Remove old g

---

REQUIRE

I'm not sure if this will run successfully without a new tag, but let's see.

Update REQUIRE for NLSolversBase.

---

test/alphacalc.jl
test/api.jl
test/runtests.jl

I forgot to enable the API tests in #59 ...
Also added another test.
Is there a way to check coverage without pushing to remote?

Enable api tests + other

---

src/api.jl
src/backtracking.jl
src/basic.jl
src/hagerzhang.jl
src/morethuente.jl
src/strongwolfe.jl
src/types.jl

Rebasing with #58 was a bit of a mess

Fix deprecations from femtocleaner

---

src/LineSearches.jl
src/backtracking.jl
src/hagerzhang.jl
src/morethuente.jl
src/static.jl
src/strongwolfe.jl

This shows how it could look.
There is a slightly annoying thing here, and that is that there will be a minor increase in cost if there's a an fg! method available, so we might want to allow for passing in phi, dphi, phi_dphi?

Univariate-ize backatracking and strongwolfe.

---

src/LineSearches.jl
src/hagerzhang.jl
test/runtests.jl

This is tracking the Univariatize pull request:
https://github.com/JuliaNLSolvers/LineSearches.jl/pull/86

v0.7 Depwarns

---

src/LineSearches.jl
src/backtracking.jl
src/hagerzhang.jl
src/initialguess.jl
src/morethuente.jl
src/strongwolfe.jl

Sister PR to https://github.com/JuliaNLSolvers/Optim.jl/pull/568.

Native complex numbers

---

src/initialguess.jl
test/initial.jl

InitialStatic currently does the wrong thing when scaling against the step direction. I thought it's better to keep this separate from #97

Fix InitialStatic bug

---

src/initialguess.jl

The current promotion breaks if state.s is complex

Force eltype state.s real for complex support

---

src/LineSearches.jl

We don't have LineSearchResults anymore, but we do have LineSearchException.

Fix exports

---

docs/generate.jl
docs/make.jl
docs/src/examples/customoptimizer.jl
docs/src/index.md
docs/src/reference/initialstep.md
docs/src/reference/linesearch.md
src/morethuente.jl
src/static.jl
test/REQUIRE
test/examples.jl
test/runtests.jl

Here's an attempt at introducing documentation in combination with Literate examples.
I propose that we introduce docs in three steps (if you are okay with making docs this way @pkofod )
1. Merge this and check out what the docs look like
2. Move the Optim examples in the README to a Literate.jl example
3. Possibly write a larger manual for each of the line search methods (and step length guesses)

Introduce docs

---

src/initialguess.jl

Some relaxations and type annotation changes.

---

src/initialguess.jl
test/initial.jl

Only return alpha in _hzI12

---

src/backtracking.jl
test/runtests.jl

Fix for external constructor of BackTracking

---

src/strongwolfe.jl
test/issues.jl

It returned the derivative instead of the value. Fixes #151

Fix strong wolfe branch.
