src/LineSearches.jl, src/api.jl, src/backtracking_linesearch.jl, src/hz_linesearch.jl, src/interpolating_linesearch.jl, src/mt_linesearch.jl, src/types.jl, test/runtests.jl
Ref discussion in JuliaOpt/Optim.jl#277. 
It is unlikely that the linesearch algorithms will get ambiguity clashes with other packages, so we remove the `AbstractDifferentiableFunction` type requirement.
=> Let df be Any

src/LineSearches.jl, src/backtracking_linesearch.jl, test/runtests.jl
This PR adds a second backtracking line search, `interpbacktrack_linesearch!` which, instead of an a *= rho update performs an interpolation step; this is highly efficient for some problems; see QCG and QLBFGS in the following figure (from my own research); 
It also outperforms HZ and MT line-search for some more standard model problems.  In general, it is no worse than standard backtracking, which I left only for the sake of compatibility. I would actually recommend to remove standard backtracking altogether and replace it with `interpbacktrack`.
=> Backtracking line search with interpolation

src/LineSearches.jl, src/backtracking.jl, src/deprecate.jl, src/hagerzhang.jl, src/morethuente.jl, src/types.jl
The hagerzhang and backtracking algorithms have a maximum iterations limit. 
Currently, it just throws an error. It would be more useful to throw an exception that stores the status of the linesearch.
=> WIP: Throw LineSearchException on max iterations

NEWS.md, README.md, src/LineSearches.jl, src/backtracking.jl, src/deprecate.jl, test/alphacalc.jl, test/backtracking.jl, test/runtests.jl
I've updated the backtracking algorithm to use either quadratic or cubic interpolation as described in Nocedal and Wright. Parameters are taken from there and from "Numerical Methods for Unconstrained Optimization and Nonlinear Equations" by Dennis and Schnabel, page 325.
This might break people's code, as I've updated the parameter list list for the algorithm (sorting out #9 will make changes like this much smoother)
Closes #13
=> RFC: Implement cubic backtracking

src/backtracking.jl, test/backtracking.jl
bt3! has a serious bug, as it does not store the initial step length. The first cubic interpolation then falsely uses `alpha0 = 0`, as all the Optim solvers set `lsr.alpha[1] = zero(T)`
=> Store initial alpha step

src/backtracking.jl
In bt3, don't create unecessary arrays
=> Calculate a,b directly

src/static.jl, test/alphacalc.jl, test/runtests.jl
For the Static linesearch, I have use cases where it is useful to have a step size that is static, relative to the direction norm.
=> Allow scaled versions of Static

REQUIRE, src/LineSearches.jl, src/backtracking.jl
In case something goes wrong during the interpolation step.
=> Use NaNMath

src/backtracking.jl, src/morethuente.jl
Also adds some `@inbounds` steps to BackTracking
=> Halve step in MoreThuente if initial step generates nonfinite values

NEWS.md, src/morethuente.jl
After looking through the MoreThuente code, I found that the original translation from the MATLAB code has a bug in it. There are several lines in `cstep` where a value `s = max(theta, dgx,dg)` is calculated. In the original [FORTRAN](http://www.cs.umd.edu/~oleary/LBFGS/FORTRAN/linesearch.f) and [MATLAB](https://github.com/andrewssobral/mtt/blob/master/libs/poblano_toolbox_1.1/cstep.m#L170)  codes, however, this is set to `s = max(abs(theta), abs(dgx), abs(dg))`.
I caught this when an optimization problem I was running broke down. It is a high-dimensional problem, and I can't replicate it in a test as the input values to the line search are shown in pretty-mode, and small changes in the eight decimal place mean that the problem does not appear...
There also seems to be a weird choice in …
=> Fixes to MoreThuente

src/initialguess.jl, src/morethuente.jl, src/static.jl
Currently, some of the algorithms call `norm` on the step directions or gradients, however, if we work with input objects such as `Array{Float64,3}`, then there is no norm function. To handle this, I changed to calling `vecnorm`. 
@antoine-levitt @cortner Is `vecnorm` a sensible norm to use when you optimize with inputs being complex numbers and/or from manifolds? Or do we need to support a user-defined norm function for these cases (in the future)?
BackTracking and HagerZhang already use `vecnorm`.
=> Use vecnorm

README.md, src/static.jl, test/alphacalc.jl, test/runtests.jl
This should remove the final barrier for us to fully univariatise the line searches.
The `scaled=true` feature can still be achieved by using `InitialStatic(scaled=true)` together with `Static()`
=> Remove scaling from Static 

src/backtracking.jl, src/static.jl
We should probably add some sort of debug / verbosity flag here to warn if this happens. (Future work :p )
=> Ensure function value is finite for Static step

src/hagerzhang.jl
Fixes a bug introduced in  #86
=> Return phi and not dphi in HZ

examples/customoptimizer.jl, src/backtracking.jl, test/examples.jl, test/runtests.jl
This provides an example of how to use LineSearches with algorithms that are not within the Optim/NLsolve universe.
I wrote it in the Literate.jl style, so that we can turn it into Docs or Notebooks to make it easier for people to try these things out.
This requires #90 and #106 to work.
=> Provide usage example with custom optimization algorithms

docs/generate.jl, test/examples.jl
Travis, AppVeyor, and CIBot all fail when there are breaking changes between LineSearches and downstream packages, such as Optim, that are also used in the examples.
I managed to filter on Travis and AppVeyor, but I don't know how to filter on CIBot. Instead of filtering tests based on CI environment, we'll just have to remember to add the tests back when the most recent downstream application works.
=> Don't filter example tests based on environment.

src/backtracking.jl, src/hagerzhang.jl, src/morethuente.jl, test/alphacalc.jl
The values of ϕ_0 and dϕ_0 are ϕ(0), dϕ(0), not ϕ(\alpha_0)).
It is a bit confusing to use α_0  as the initial guess, because it means that we think ϕ_0 refers to the value at the initial guess. Maybe we should change all α0 / α_0's to αinitial?
=> Fix \phi_0 and d\phi_0 values

docs/src/examples/customoptimizer.jl, src/backtracking.jl, src/hagerzhang.jl, src/morethuente.jl, src/static.jl
=> Unify interface for linesearches

src/initialguess.jl, test/initial.jl
=> Fix InitialConstantChange

docs/generate.jl, test/REQUIRE, test/examples.jl
Next time we hit a breaking change in LineSearches we'll have to remove these tests (and possibly Optim from REQUIRE) again. A bit of a faff, but more tests > fewer tests.
=> Test Optim examples

.travis.yml, REQUIRE, appveyor.yml, docs/generate.jl, docs/make.jl, docs/src/examples/customoptimizer.jl, docs/src/examples/optim_initialstep.jl, docs/src/examples/optim_linesearch.jl, src/LineSearches.jl, src/backtracking.jl, src/hagerzhang.jl, src/initialguess.jl, src/morethuente.jl, src/static.jl, src/strongwolfe.jl, test/REQUIRE, test/alphacalc.jl, test/arbitrary_precision.jl, test/examples.jl, test/initial.jl, test/runtests.jl
I just want to see what femtocleaner has to say here (Ref  #126 )
=> Require Julia 0.7

.gitignore, .travis.yml, docs/Project.toml, docs/generate.jl, docs/make.jl, test/REQUIRE, test/runtests.jl
Following https://github.com/JuliaNLSolvers/Optim.jl/pull/676
=> Make docs a project and run as a Travis job

src/hagerzhang.jl, src/initialguess.jl, test/initial.jl
This PR closes #133, #134, and #135. There is one error I am getting in LineSearches tests which seems unrelated to the changes made. Optim tests pass. I will look into this further. Also, I need to check if other places error when the search direction is not a descent direction and try to make it robust to computational error when starting at the optimal solution. Finally, someone please comment on my use of `mayterminate` since I don't understand how it will be used apart from checking when the quadratic step is taken.
=> [WIP] Fix HagerZhang bugs

.gitignore, Project.toml, docs/src/index.md, docs/src/reference/linesearch.md, src/LineSearches.jl, src/backtracking.jl, src/hagerzhang.jl, src/morethuente.jl, src/static.jl, src/strongwolfe.jl, src/types.jl, test/REQUIRE, test/TestCases.jl, test/captured.jl, test/runtests.jl
Also includes the failing case in PR#174.
This is minimally modified from the code provided by @mateuszbaran (who I've listed as a co-author).
~~One thing that seems missing: documentation on how to capture the specific values tried by the failing line search method. I'm not broadly familiar with them all, is there any good guidance on that? Or should we add a `cache::Bool` option to them all?~~
Once this gets merged, we should first capture any other problem reports and then start trying to fix the failures.
Closes #102
=> Add LineSearchTestCase
